=== jls2510/scratch-java/src/main/resources/xml/webscheduler-update.dtd
<?xml version='1.0' encoding='UTF-8'?>

  <!-- times are GMT
       singleton-date is in YYYYMMDD format, where MM is 01-12 and DD is 01-31
       duration and relative-start-time are offset times i.e. hh:mm:ss:ff
       action is one of create-or-update, delete, reconcile-daypart, reconcile-day
       reconcile-day finds all the dayparts that meet the criteria, and assumes
       that all the shows have been provided
       (reconcile-daypart is used to look for necessary deletes of shows)
  -->

   <!ELEMENT webscheduler-update (action, network, time-range, match-rule*, event-list?, event?, hardware*)>
   <!ELEMENT action (#PCDATA)>
   <!ELEMENT network (#PCDATA)>
   <!ELEMENT time-range (singleton-date)>
   <!ELEMENT singleton-date (#PCDATA)>
   <!ELEMENT match-rule (binding*)>

   <!ATTLIST webscheduler-update
        source CDATA #IMPLIED >

   <!-- event-list shows the complete list of shows for reconcile-daypart
        it also can serve as a "position-after" element for create-or-update
   -->
   <!ELEMENT event-list (match-rule*)>
   <!ELEMENT event (binding*, event*)>
   <!ELEMENT binding (#PCDATA)>
   <!ELEMENT hardware ((facility | playback | record | dup-channel), binding*)>
   <!ELEMENT facility (#PCDATA)>
   <!ELEMENT playback (singleton-date, match-rule*)>
   <!ELEMENT record (EMPTY)>
   <!ELEMENT dup-channel (#PCDATA)>

  <!--I made duration optional for tied events -->

  <!-- start-time (a frame time ALWAYS WITH a time zone) is used only to position the show element in the daypart;
       relative-start-time is what you want otherwise if you need a start time
       GPI type preserves the SMPTE GPI resource name for use in structural transformations
       debug-context is used e.g. to remember which SMPTE event produced this webscheduler event
       -->
   <!ATTLIST event
        class-name CDATA #REQUIRED
        duration CDATA #IMPLIED
        relative-start-time CDATA #IMPLIED
        overrun CDATA #IMPLIED
        external-id CDATA #IMPLIED
        start-time CDATA #IMPLIED
        gpi-type CDATA #IMPLIED
        primary-event-id CDATA #IMPLIED
        debug-context CDATA #IMPLIED>
   <!ATTLIST binding role CDATA #REQUIRED purpose CDATA #IMPLIED >
   <!--  time does a match on a container's time range and looks for a binding (you can use
         the "magic value" null )-->
   <!--  start-time is in a standard frame-time format "mm/dd/yyyy hh:mm:ss:ff zz"    -->
   <!ATTLIST match-rule
        match (eventid|child|clone|contingency|time|billingReference|basisNumber) #REQUIRED
        start-time CDATA #IMPLIED >
   <!ATTLIST record breakin (pre|post) #REQUIRED >
   <!ATTLIST dup-channel breakin (pre|post) #REQUIRED >

=== jls2510/scratch-java/src/main/resources/xml/test2.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE webscheduler-update SYSTEM "webscheduler-update.dtd">

<webscheduler-update source="webSchedClient">

  <!-- valid actions are create-or-update, reconcile-daypart and delete -->
  <action>create-or-update</action>

  <!-- this section navigates to the appropriate show (if it exists) -->
  <network>NBC</network>
  <time-range><singleton-date>20350923</singleton-date></time-range>

  <match-rule match="child" >
        <binding role="Event Title">EARLY TODAY</binding>
  </match-rule>
  <match-rule match="child" >
        <binding role="Event Title">Clearance NOT NEEDED</binding>
  </match-rule>


  <!-- this section describes the structure of the show-->

  <event class-name="Show"  duration="00:30:00:00" overrun="00:00:00:00" external-id="4412950" >
    <binding role="Display Name" >Clearance NOT NEEDED</binding>
    <binding role="Event Title" >Clearance NOT NEEDED</binding>
    <binding role="TMS ID" >TMSID0001</binding>
    <binding role="Day_Part" >DT</binding>
    <binding role="Network" >1</binding>
    <binding role="Season Code" >10</binding>
    <binding role="Nielsen Name" >Clearance NOT NEEDED</binding>
    <binding role="Basis Number" >1029</binding>
    <binding role="Traffic Show ID" >4412750</binding>
    <binding role="Event Process Type" >SH</binding>
    <binding role="Basis Alt Number" >02</binding>
    <binding role="Event Code" >SH</binding>
    <event class-name="Segment"  duration="00:30:00:00" overrun="00:00:00:00"  external-id="17435948" >
    <binding role="Event Title" >Segment</binding>
    <binding role="Event Process Type" >SH</binding>
    <binding role="TimeCode" >00300000</binding>
    <binding role="Event Code" >SH</binding>
    <binding role="LongFormMaterial_ID" >LFMATID0001</binding>
    <binding role="Network" >1</binding>
    </event>
    <event class-name="GPIGroup"  duration="00:00:00:00"   external-id="17436052" >
    <binding role="GPI Group Name" >Program Start</binding>
    <binding role="Event Title" >Program Start</binding>
    <event class-name="GPI"  duration="00:00:01:00" overrun="00:00:00:00" relative-start-time="00:00:00:00" external-id="17436053" >
    <binding role="GPI Action Mode" >ON</binding>
    <binding role="Offset From End" >N</binding>
    <binding role="Event Title" >ProgramStart</binding>
    <binding role="GPI Resource Name" >ProgramStart</binding>
    </event>
    </event>
  </event>


</webscheduler-update>

=== jls2510/scratch-java/src/main/resources/xml/test1.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE webscheduler-update SYSTEM "webscheduler-update.dtd">

<webscheduler-update source="webSchedClient">

  <!-- valid actions are create-or-update, reconcile-daypart and delete -->
  <action>create-or-update</action>

  <!-- this section navigates to the appropriate show (if it exists) -->
  <network>NBC</network>
  <time-range><singleton-date>20350923</singleton-date></time-range>

  <match-rule match="child" >
        <binding role="Event Title">PRIMETIME 02</binding>
  </match-rule>
  <match-rule match="child" >
        <binding role="Event Title">Show 1113</binding>
  </match-rule>


  <!-- this section describes the structure of the show-->

  <event class-name="Show"  duration="01:00:00:00" overrun="00:00:00:00" external-id="13387547" >
    <binding role="Nielsen Name" >Show 1113</binding>
    <binding role="Basis Number" >1113</binding>
    <binding role="Traffic Show ID" >13385579</binding>
    <binding role="Display Name" >Show 1113</binding>
    <binding role="Event Title" >Show 1113</binding>
    <binding role="Basis Alt Number" >03</binding>
    <binding role="Day_Part" >DT</binding>
    <binding role="Event Code" ></binding>
    <binding role="Network" >1</binding>
    <binding role="Season Code" >13</binding>
    <event class-name="GPIGroup"  duration="00:00:00:00"   external-id="13387548" >
    <binding role="GPI Group Name" >SCTE Program Start</binding>
    <binding role="Event Title" >SCTE Program Start</binding>
    <event class-name="GPI"  duration="00:00:01:00" overrun="00:00:00:00" relative-start-time="00:00:00:00" external-id="13387549" >
    <binding role="GPI Action Mode" >ON</binding>
    <binding role="Offset From End" >N</binding>
    <binding role="Event Title" >70</binding>
    <binding role="GPI Resource Name" >70</binding>
    </event>
    </event>
  </event>


</webscheduler-update>
